In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 

url = "https://stockanalysis.com/stocks/"

response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser') 

    tbody = soup.find('tbody')

    companies = {}
    tr = tbody.find_all('tr', class_='svelte-utsffj')
    for row in tr:
        company_name_td = row.find('td', class_='slw svelte-utsffj')
        ticker_td = row.find('td', class_='sym svelte-utsffj')

        if company_name_td and ticker_td:
            company_name = company_name_td.text.strip()
            ticker_symbol = ticker_td.text.strip()

            companies[company_name] = ticker_symbol


else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")

def export_data(companies):
    companies2 = list(companies.items())
    
    df = pd.DataFrame(companies2, columns=['company', 'ticker'])
    display(df)

export_data(companies)

                               company ticker
0           Agilent Technologies, Inc.      A
1                    Alcoa Corporation     AA
2                ATA Creativity Global   AACG
3      Ares Acquisition Corporation II   AACT
4                Aadi Bioscience, Inc.   AADI
..                                 ...    ...
493                     AvePoint, Inc.   AVPT
494  Anteris Technologies Global Corp.    AVR
495                        Avnet, Inc.    AVT
496        Aerovate Therapeutics, Inc.   AVTE
497                      Avantor, Inc.   AVTR

[498 rows x 2 columns]

In [5]:
df.to_csv("company_tickers.csv", index=False)

In [7]:
df.loc[ df['ticker'] == 'AAPL', 'company' ] = 'Apple'
print(df.loc[df['ticker'] == 'AAPL', 'company'])

11    Apple
Name: company, dtype: object

In [10]:
#df.loc[ df['ticker'] == 'MSFT', 'company' ] = 'Apple'
print(df.loc[df['ticker'] == 'MSFT', 'company'])

Series([], Name: company, dtype: object)

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

url = "https://stockanalysis.com/stocks/"

driver = webdriver.Chrome()  
driver.get(url)

companies = {}

while True:
    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.TAG_NAME, "tbody"))
        )
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        tbody = soup.find('tbody')
        
        tr = tbody.find_all('tr', class_='svelte-utsffj')
        for row in tr:
            company_name_td = row.find('td', class_='slw svelte-utsffj')
            ticker_td = row.find('td', class_='sym svelte-utsffj')

            if company_name_td and ticker_td:
                company_name = company_name_td.text.strip()
                ticker_symbol = ticker_td.text.strip()
                companies[company_name] = ticker_symbol

        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//button[contains(., "Next")]'))
        )
        next_button.click()

        time.sleep(2)

    except Exception as e:
        print("No more pages to scrape or encountered an error:", e)
        break

driver.quit()

def export_data(companies):
    companies2 = list(companies.items())
    df = pd.DataFrame(companies2, columns=['company', 'ticker'])
    df.to_csv("company_tickers.csv", index=False)
    print("Data has been exported to company_tickers.csv")
    display(df)

export_data(companies)

No more pages to scrape or encountered an error: Message: element click intercepted: Element <button class="controls-btn xs:pl-1 xs:pr-1.5 bp:text-sm sm:pl-3 sm:pr-1">...</button> is not clickable at point (615, 632). Other element would receive the click: <div class="fixed left-0 top-0 z-[99] flex h-screen w-screen items-center justify-center bg-gray-500/50">...</div>
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x00007FF6ECDFFB05+28789]
	(No symbol) [0x00007FF6ECD686E0]
	(No symbol) [0x00007FF6ECC0592A]
	(No symbol) [0x00007FF6ECC60FDE]
	(No symbol) [0x00007FF6ECC5EA7C]
	(No symbol) [0x00007FF6ECC5BC46]
	(No symbol) [0x00007FF6ECC5ABA1]
	(No symbol) [0x00007FF6ECC4CD60]
	(No symbol) [0x00007FF6ECC7F43A]
	(No symbol) [0x00007FF6ECC4C5B6]
	(No symbol) [0x00007FF6ECC7F650]
	(No symbol) [0x00007FF6ECC9F654]
	(No symbol) [0x00007FF6ECC7F1E3]
	(No symbol) [0x00007FF6ECC4A938]
	(No symbol) [0x00007FF6ECC4BAA1]
	GetHandleVerifier [0x00007FF6ED13933D+3410093]
	GetHandleVerifier [0x00007FF6ED14E7DD+3497293]
	GetHandleVerifier [0x00007FF6ED142A73+3448803]
	GetHandleVerifier [0x00007FF6ECEC7BBB+848171]
	(No symbol) [0x00007FF6ECD73C3F]
	(No symbol) [0x00007FF6ECD6F6E4]
	(No symbol) [0x00007FF6ECD6F87D]
	(No symbol) [0x00007FF6ECD5ED49]
	BaseThreadInitThunk [0x00007FFF8C0D259D+29]
	RtlUserThreadStart [0x00007FFF8C88AF38+40]

Data has been exported to company_tickers.csv

                              company ticker
0          Agilent Technologies, Inc.      A
1                   Alcoa Corporation     AA
2               ATA Creativity Global   AACG
3     Ares Acquisition Corporation II   AACT
4               Aadi Bioscience, Inc.   AADI
...                               ...    ...
4947                  U Power Limited   UCAR
4948     United Community Banks, Inc.    UCB
4949            uCloudlink Group Inc.    UCL
4950       Ultra Clean Holdings, Inc.   UCTT
4951                      Udemy, Inc.   UDMY

[4952 rows x 2 columns]